### ISSUE TITLE
[Suggestion]: Add Docker Compose

### ISSUE THREAD

**Issue by WeirdPtr** [LeagueOfPoro/CapsuleFarmerEvolved#128]
### What is your idea?

Adding compose instructions would simply make the Installation Instruction Wiki more complete.

### What should happen?

Create a new Docker Compose Installation Step and add Compose Steps.

Heres a version that could be used:

```yaml
version: '3.3'
services:
    capsulefarmer:
        container_name: capsule-farmer
        image: 'leagueofporo/capsulefarmer:master'
        restart: unless-stopped
        volumes:
            - '/path/to/config.yaml:/config/config.yaml'
```

### My request is not a question

- [X] I acknowledge that this issue is not a question or a bug request.
