### ISSUE TITLE
[Wiki]: Add Docker Compose

### ISSUE THREAD

**Issue by WeirdPtr** [LeagueOfPoro/CapsuleFarmerEvolved#129]
### What is your request?

Adding compose instructions would simply make the Wiki more complete/easy to use.

Heres a version that could be used:

```yaml
version: '3.3'
services:
    capsulefarmer:
        container_name: capsule-farmer
        image: 'leagueofporo/capsulefarmer:master'
        restart: unless-stopped
        volumes:
            - '/path/to/config.yaml:/config/config.yaml'
```

### My request is not related to the application it self

- [X] I acknowledge that this issue is not related to the application and is in fact a wiki request.
